### ISSUE TITLE
Issue with the absentee_second.py program

### ISSUE THREAD

**Issue by dbc2201** [amirkhan1092/python38-GLA#2]
I tried it with a CSV file from one of the sections but it shows  
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/divyanshb/PycharmProjects/python38-GLA-dbc/absentee_second.py", line 21, in calc
    data_main = pd.read_csv(root.main_file)
  File "/usr/local/lib64/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib64/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib64/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib64/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib64/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File secZ.csv does not exist: 'secZ.csv'
```

**Comment by amirkhan1092** [comment]
for this you should have first all the email-id of students with roll number in csv format and placed in current local folder of python file
